apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: demo-loan-nn-onnx-beta
    serving.kserve.io/deploymentMode: ModelMesh
  name: demo-loan-nn-onnx-beta
  labels:
    name: demo-loan-nn-onnx-beta
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
        version: '1'
      runtime: ovms
      storage:
        key: aws-connection-rhods-public
        path: trusty/loan_model_beta.onnx
