apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: demo-loan-nn-onnx-alpha
    serving.kserve.io/deploymentMode: ModelMesh
  name: demo-loan-nn-onnx-alpha
  namespace: trustyai-e2e-modelmesh
  labels:
    name: demo-loan-nn-onnx-alpha
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
        version: '1'
      runtime: mlserver-0.x
      storageUri: "https://github.com/RobGeada/trustyai_april12_demo/blob/main/resources/loan_model_alpha.onnx?raw=true"
      
