kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: odh-data-connection
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: aws-connection-${ODH_DATA_CONNECTION_NAME}
      labels:
        opendatahub.io/dashboard: 'true'
        opendatahub.io/managed: 'true'
      annotations:
        opendatahub.io/connection-type: s3
        openshift.io/display-name: ${ODH_DATA_CONNECTION_NAME}
    data:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    type: Opaque
parameters:
  - name: ODH_DATA_CONNECTION_NAME
    required: true
  - name: AWS_ACCESS_KEY_ID
    required: true
  - name: AWS_DEFAULT_REGION
    required: true
  - name: AWS_S3_BUCKET 
    required: true
  - name: AWS_S3_ENDPOINT
    required: true
  - name: AWS_SECRET_ACCESS_KEY
    required: true
